### ISSUE TITLE
Use of unresolved identifier 'translations' in ValueSet+Localization.swift when XCode upgraded to Swift 3.1

### ISSUE THREAD

**Issue by ro-lo** [smart-on-fhir/Swift-FHIR#8]
I made the mistake of updating my macOS and XCode versions today and now I'm getting a problem while trying to build my project.

It appears it doesn't understand the translations object in the extension of Array where Element == ValueSetComposeIncludedConceptDesignation

Perhaps I don't really know how to set it to compile with Swift 3.0 or it's not that easy, so I'm kinda stuck at this point.

Hopefully you see the same thing and can help fix this problem :)

Thanks so much for your help!

**Comment by xmlmodeling** [comment]
Thanks for reporting this issue!  A fix was committed for Swift 3.1 and you should now be good to go with Xcode 8.3.

**Comment by aechika** [comment]
This seems to be resolved only when using: 
pod 'SMART', '~> 3.0'
but still fails when using
pod 'FHIR', '~> 3.0'

Is there any way to fix it just for the FHIR pod?
